INSERT INTO USER_DETAILS(USER_ID, USERDOB, USER_NAME)
VALUES(1, current_date(), 'Kaushik');

INSERT INTO USER_DETAILS(USER_ID, USERDOB, USER_NAME)
VALUES(2, current_date(), 'Durvas');

INSERT INTO USER_DETAILS(USER_ID, USERDOB, USER_NAME)
VALUES(3, current_date(), 'Princy');